### ISSUE TITLE
Encapsulate rules and facts in knowledge base

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/vlog4j#21]
Sets of rules and facts should be encapsulated in a knowledge base object that can also be used in KB transformations and in the reasoner. A listener pattern is needed to keep the reasoner aware of changes to this object.

**Comment by irina-dragoste** [comment]
I have some questions related to the desired behavior of the reasoner, when a KB has been modified after loading:

Reasoning Scenario:
1. reasoner.load(kb)
2. kb.addFacts(some facts)
3. reasoner.reason()

Do we want, inside reasoner.reason(), to re-load the database and call reason() again?
If so, I think this behavior should be consistent when querying:

Query Scenario A:
1. reasoner.load(kb)
2. kb.addFacts(some facts)
3. reasoner.query(q)

Query Scenario B:
1. reasoner.load(kb)
2. reasoner.reason()
2. kb.addFacts(some facts)
3. reasoner.query(q)

In Query Scenario A: 
inside reasoner.query, if the database has been modified since last load(), do we want to re-load the internal reasoner, for the query result to reflect the changes?

In Query Scenario B:
inside reasoner.query, if the database has been modified since loast reason(), do we want to re-load the internal reasoner and CALL REASON() AGAIN, for the query result to reflect the changes?

**Comment by irina-dragoste** [comment]
Do we want to keep resetReasoner() as a public method, or should this be called internally whenever load(KB) is called?

**Comment by irina-dragoste** [comment]
A `KnowledgeBase` object encapsulates all the rules and facts that are currently added to the `Reasoner`: `addRules`, `addFacts`, `addFactsFromDataSource`.

`Reasoner` would have a `Reasoner(KnowledgeBase kb)` (single) constructor, and the `KnowledgeBase` field of a reasoner will be immutable.

`Reasoner#load()` method calls `vlog reasoner.start()`.
If `this.load()` has not been called yet by the current `Reasoner` object, it will be called inside `this.reason()`, such that reasoning will always be with respect to the current  `KnowledgeBase`. 

The `Reasoner`'s behaviour at query answering, if the `KnowledgeBase` has been modified after loading, depends on the `Reasoner` settings: either throw an exception, or log a warning that completenss is not guaranteed.

**Comment by irina-dragoste** [comment]
> The Reasoner's behaviour at query answering, if the KnowledgeBase has been modified after loading, depends on the Reasoner settings: either throw an exception, or log a warning that completenss is not guaranteed.

Currently, query answering returns a Correctness result, which states the correctness of the answers with respect to the current KnowledgeBase

**Comment by irina-dragoste** [comment]
solved in Knowledge base #83.
