### ISSUE TITLE
BUG: Conclusion not reached

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#39]
Hello everyone,

I have another bug to report. Unless I misunderstood something (which is a very valid possibility), this [example](https://github.com/Adrian-Bielefeldt/wcd/blob/extractionConsolidation/src/main/java/experiment/MinimalExample.java) should apply the rule violation (line 60) once and thus give an output for the third query (line 68). However, it does not.

Thanks for any assistance you can offer,

Adrian

**Comment by irina-dragoste** [comment]
The rule violation is actually not applicable. Looking for a substitution that matches the rule body, we have s->id30, o->id31, i->Q1, but v cannot be matched (it has to match Q1 and Q2 at the same time).

It would be applicable if instead of
Atom triple1 = Expressions.makeAtom(tripleEDB, id30, Q1, P209, Q1);
Atom triple2 = Expressions.makeAtom(tripleEDB, id31, Q1, P209, Q2);

you would have
Atom triple1 = Expressions.makeAtom(tripleEDB, id30, Q1, P209, Q1);
Atom triple2 = Expressions.makeAtom(tripleEDB, id31, Q1, P209, Q1);
or 
Atom triple1 = Expressions.makeAtom(tripleEDB, id30, Q1, P209, Q2);
Atom triple2 = Expressions.makeAtom(tripleEDB, id31, Q1, P209, Q2);

**Comment by Adrian-Bielefeldt** [comment]
There was indeed a typo in my example, but not in the triples. Instead of

// tripleEBD(?o, ?i, http://www.wikidata.org/entity/P209, ?w)
Atom tripleEDB_OIpV = Expressions.makeAtom(tripleEDB, o, i, P209, v);

I should have written

// tripleEBD(?o, ?i, http://www.wikidata.org/entity/P209, ?w)
Atom tripleEDB_OIpW = Expressions.makeAtom(tripleEDB, o, i, P209, w);

With this mistake corrected I still do not get the expected result. It is easily possible I am mistaken again, but I cannot see it.

Thanks for the help.

**Comment by irina-dragoste** [comment]
You are right, the last argument of **violation_tripleSIpV** should be the value of **Q1**, but is instead the value of **id30**. It is a bug, we must investigate it.
