### ISSUE TITLE
Segmentation fault caused by rules with constants

### ISSUE THREAD

**Issue by chlewe** [knowsys/vlog4j#40]
I wrote a simple program that uses rules with terms consisting of an alternation of constants and variables. For instance, `0X1Y`is such a term, where `X` and `Y` are variables and `0` and `1` are constants. VLog(4J) seems to not be able to work with these kinds of rules and produces a segmentation fault.

[I wrote a minimal example that illustrates the issue.](https://gist.github.com/chlewe/572480501de9362442eb9bb457cf9c8f)

[I also tried to work with VLog directly and was able to provoke weird behaviour, albeit not a segmentation fault. Maybe this is related to the issue here.](https://github.com/karmaresearch/vlog/issues/2)

**Comment by irina-dragoste** [comment]
Bug fixed on the master branch version of vlog4j-base (that has not been yet released on Maven): https://github.com/karmaresearch/vlog. We will soon make a new release with all bug fixes and feature improvements.

In order to use the unreleased code, you can operate vlog4j in development mode. Download the master branch of the github code of vlog4j locally, and follow the instructions in script build-vlog-library.sh. Line "export CC=gcc-5 && export CXX=g++-5" is optional.
