### ISSUE TITLE
ERROR  SIZETUPLE needs to be set to at least 22!

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#42]
Hello everyone,

I was wondering what this error means. I was splitting a rule with dozens of variables into smaller chunks and got this error during it. It seems to me the number of variables in a rule is restricted to 16? If so, it would be nice to have an error message that is a bit more informative.

Thanks,

Adrian

**Comment by mkroetzsch** [comment]
Ok, but do you really need a vector? Even the size of an array can be selected at runtime. What vector adds on top of this would be that you can change the size of an existing record. But this should never be needed. It would already be nice if the size could be changed for each individual run of vlgo without having to recompile.

If the limit is going to remain hard, then we should at least improve the interplay with VLog4j. We could implement the limit on the higher level (but for this we would need to have a way to fetch the value of the limit from vlog). Maybe there are also other compile-time settings that would be useful for Vlog4j to fetch in order to adjust its features?

**Comment by CerielJacobs** [comment]
In C++, I don't think you can select the size of an array at runtime. It should be a compile-time constant.

**Comment by mkroetzsch** [comment]
Oh, I see. Maybe there could be several pre-compiled cases, so that the code can chose the most suitable one at runtime? A fixed size of 20 is already much larger than usually needed. Could one have special implementations for arity 1, 2 3, atmost 10, and a vector for the cases no covered by any fixed option?

**Comment by CerielJacobs** [comment]
I'm now experimenting with a version that no longer has this limit, using dynamic allocation. I still need to do more testing, but at least for DBpedia, there seems to be no significant slowdown in materialization, and memory consumption is actually just a little bit lower (but may be a little bit higher when the arity is actually high).

**Comment by irina-dragoste** [comment]
@Adrian-Bielefeldt could you check that this problem is fixed with the new master branch version of Vlog? I would like to close the issue after your confirmation.

**Comment by Adrian-Bielefeldt** [comment]
This issue is resolved.
