### ISSUE TITLE
Data source {0} for predicate {1} is empty:

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#44]
Hello everyone,

I get this error message when one of my .csv-files is empty - so far, so good. Since it does not tell me which data source I guess this is a bug and is supposed to output the source and predicate instead of {0} and {1}.

Greetings,

Adrian

**Comment by irina-dragoste** [comment]
Hello, can you give us the details? I didn't manage to reproduce the error.

**Comment by Adrian-Bielefeldt** [comment]
I've created a small [example](https://github.com/Adrian-Bielefeldt/wcd/blob/extractionConsolidation/src/main/java/experiment/MinimalExample.java).

Basically, if you have a .csv-file that is completely empty (also no empty lines) and load it via CsvFileDataSource, the error message appears.

**Comment by irina-dragoste** [comment]
The example you provided throws a NullPointerException, related to [this bug](https://github.com/knowsys/vlog4j/issues/48). If you provide a parent for the file, you have to make sure the file is not just created as an object in java, but as an actual file in the file system:
               `final File file = new File("src/test/data/test.csv");
		final boolean isNewFile = file.createNewFile();
		System.out.println(file.getParent());
		System.out.println("File is created and did not already exist: " + isNewFile);
		final DataSource dataSource = new CsvFileDataSource(file);`

If you replace the lines in your example with these corresponding lines of code, the bug is not reproduced.

**Comment by Adrian-Bielefeldt** [comment]
If you create the file with `touch test.csv`, the error can be reproduced. I have found the source of the bug and fixed it [here](https://github.com/knowsys/vlog4j/pull/49).

**Comment by irina-dragoste** [comment]
Thank you for fixing it, I merged the fix.
