### ISSUE TITLE
Logging output of iterations, runtime, and derivations

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [knowsys/vlog4j#50]
In version 0.1.0, reasoning produced output like this on the console, presumably coming from VLog.
> [0xa2158b735a50e09d 2018-10-04 15:05:39] INFO  Starting full materialization
> [0xa2158b735a50e09d 2018-10-04 15:05:39] INFO  Finished process. Iterations=6
> [0xa2158b735a50e09d 2018-10-04 15:05:39] INFO  Runtime materialization = 1,543312 milliseconds
> [0xa2158b735a50e09d 2018-10-04 15:05:39] INFO  Total # derivations: 6

On the current master branch for VLog4j, this output does not exist anymore. However, it is also not part of the logging output of the reasoner - even when LogLevel.INFO is set. Since I found no issue relating to this: Is there a way to obtaint this information at the moment (or plans to make it available again)?

**Comment by irina-dragoste** [comment]
There are two kind of logs generated by vlog4j: one is the slf4j logging information for the Java org.semanticweb.vlog4j.core.reasoner.implementation.VLogReasoner class, ans is configured by the user. The other is the C++ VLog log, which is configured trough methods declared in org.semanticweb.vlog4j.core.reasoner.Reasoner interface. The output you display before is the C++ Vlog output.

By default, the log level of VLog inside the Reasoner is DEBUG, and it logs all information to the system output. In order to set a different log level, you need to call org.semanticweb.vlog4j.core.reasoner.Reasoner#setLogLevel(@NonNull LogLevel logLevel);

In order to redirrect the VLog log to a file, you need to call
org.semanticweb.vlog4j.core.reasoner.Reasoner#setLogFile(@Nullable String filePath);

This seems to works, and there are unit tests for this: https://github.com/knowsys/vlog4j/blob/master/vlog4j-core/src/test/java/org/semanticweb/vlog4j/core/reasoner/LoggingTest.java

If it does not, please give more details.

**Comment by irina-dragoste** [comment]
@Adrian-Bielefeldt  Is the above comment satisfactory? If so, I would like to close the issue.

**Comment by Adrian-Bielefeldt** [comment]
The comment is satisfactory, and I have found the output I was looking for.
